import pandas as pd
import matplotlib.pyplot as plt

def bike_cost_analysis(data_file):
    try:
        df=pd.read_csv(data_file)
        print("The following dataframe has been loaded: ", df)
    except FileNotFoundError:
        print("File not found!")
        
    print("The first few rows: ", df.head(), "\n")
    
    df["Total_revenue"]=df["Price"]*df["Number_sold"]
    total_revenue=df.groupby("Bike")["Total_revenue"].sum()
    print("The total revenue generated by selling all bikes is: ", total_revenue)
    
    total_revenue.plot(kind='bar')
    plt.xlabel('Bike model')
    plt.ylabel('Revenue per bike')
    plt.title('Revenue graph')
    plt.tight_layout()
    plt.show()
    
    bikes_sold_total=df.groupby('Bike')["Number_sold"].sum()
    print("The number of bikes sold per model: ", bikes_sold_total, '\n')
    
    bikes_sold_total.plot(kind='bar')
    plt.xlabel("Bike sold")
    plt.ylabel("Number of bikes sold")
    plt.title('Number of bikes sold graph')
    plt.tight_layout()
    plt.show()
    
    
data_file="C:\\Users\\ragha\\OneDrive\\Documents\\python elevate labs tasks\\bikes.csv"
bike_cost_analysis(data_file)
